In [24]:
import numpy as np
import pandas as pd
from scipy import linalg

In [25]:
train = pd.read_csv('PCA_train.txt',delimiter=',', names=('x','y'))
train.head()

x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0

In [32]:
class pca:
    
    def __init__(self ,new_size=1):
        self.p = None
        self.new_size = new_size
        self.matrix = None
        
    
    def fit(self,train):
        self.matrix = np.zeros((train.shape[1],train.shape[1]),dtype=float)
        self.p = np.arange(0,len(train.columns))
        new_train=self.__scatter_matrix(train)
        order_eigenvect=self.__order_eigenvectors(self.matrix)
        # return
        return np.dot(order_eigenvect.T,np.array(new_train).T)[:self.new_size]
    
    def __order_eigenvectors(self,matrix):
        eigenvalues ,eigenvectors = linalg.eig(matrix)
        '''
        Identy_matrix =np.eye((matrix.shape[0]))
        eigenvalues C-lambda*Identy_matrix

        0.0490834,1.28402771

        eigenvector if X2 is 1
        [[-1.08453681  0.92205261]
         [ 1.          1.        ]]

        '''
        eigenvectors=eigenvectors/eigenvectors[1,:]

        '''Any eigenvector v satisfies the condition:
                cov × v = ⅄ × v
        '''
        # checking  eigenvector v satisfies the condition                   
        if sum(sum((eigenvalues.real*eigenvectors-np.dot(matrix,eigenvectors))))<0.0000001:
            print("eigenvector  cov × v = ⅄ × v satisfies")
        else:
            print("eigenvector  cov × v = ⅄ × v not satisfies")


        # increasing order 
        sort_index = np.argsort(eigenvalues.real)
        # decreasing order
        sort_index=sort_index[::-1]

        #Once eigenvectors are found from the covariance matrix, the next step is to order them by 
        return eigenvectors[:,sort_index]
    
    def __scatter_matrix(self,train):
        new_train=train-train.mean(axis=0)
        for i,col_i in zip(self.p,new_train.columns):
            for j,col_j in zip(self.p,new_train.columns):
                if self.matrix[i][j] != 0:
                    continue
                else: 
                    # covarience for col_i and col_j
                    value_col_i = new_train[col_i]
                    value_col_j = new_train[col_j]
                    cov_col_i_col_j =sum((value_col_i*value_col_j))/(len(value_col_i)+0.0-1)
                    self.matrix[i][j] = cov_col_i_col_j
                    self.matrix[j][i] =cov_col_i_col_j

        return new_train


In [36]:
model = pca(new_size=1)
d=model.fit(train)
print(d.shape)

d

eigenvector  cov × v = ⅄ × v satisfies
(1, 304)


array([[-3.55705473e+00, -5.01390969e+00, -5.38203412e+00,
         2.16973188e+00, -6.87456967e+00, -9.01642582e+00,
        -9.28416845e-01, -4.79415461e+00,  1.60122543e+00,
         1.32537297e+01,  3.76173483e+00, -2.24266677e+00,
        -2.46069443e+00, -1.58594989e+00,  6.94838976e+00,
        -8.77931766e+00,  2.19849549e+00, -3.10047862e-02,
        -1.60929701e-02,  3.87867595e+00, -4.83629007e+00,
        -1.10195346e+00, -3.33376257e+00,  9.34913102e-01,
         5.19824143e+00,  1.54238087e+00,  2.48189339e+00,
        -1.31888292e+00, -9.75826681e-01,  9.66404782e-01,
        -2.99663960e+00,  5.98988263e+00,  2.04866948e+00,
         1.71905842e+00,  8.14208799e+00,  1.84764528e+00,
         5.64625481e+00,  7.00855794e+00, -2.99297754e+00,
         5.84290613e+00,  1.84815553e+00,  2.68382418e+00,
         1.72048356e+00, -3.05413935e+00, -3.52392068e+00,
        -1.25914049e-01,  5.99178792e+00, -4.86319039e+00,
         1.77302273e+00,  5.23944542e+00,  7.30777582e+0

In [34]:
train = pd.read_csv('HT (1).csv',delimiter=',', names=([x for x in range(11)]))
train.head()

0    1     2    3     4    5     6     7     8    9    10
0  3.5  2.5  3.33  4.0  2.75  2.8  3.25  3.00  4.00  3.5  3.5
1  4.0  4.0  3.00  1.0  2.00  5.0  4.75  3.25  3.67  1.0  1.5
2  3.0  3.5  3.33  3.0  3.50  3.6  2.50  2.50  3.33  3.5  3.0
3  4.0  4.0  4.33  3.0  2.00  5.0  4.00  3.75  4.33  3.5  4.5
4  3.0  3.0  3.00  3.0  2.75  3.0  3.00  3.00  3.00  3.0  3.0

In [35]:
#new_size size of features you wants 
model = pca(new_size=2)
d=model.fit(train)
print(d.shape)
d

eigenvector  cov × v = ⅄ × v satisfies
(2, 304)


array([[-3.55705473e+00, -5.01390969e+00, -5.38203412e+00,
         2.16973188e+00, -6.87456967e+00, -9.01642582e+00,
        -9.28416845e-01, -4.79415461e+00,  1.60122543e+00,
         1.32537297e+01,  3.76173483e+00, -2.24266677e+00,
        -2.46069443e+00, -1.58594989e+00,  6.94838976e+00,
        -8.77931766e+00,  2.19849549e+00, -3.10047862e-02,
        -1.60929701e-02,  3.87867595e+00, -4.83629007e+00,
        -1.10195346e+00, -3.33376257e+00,  9.34913102e-01,
         5.19824143e+00,  1.54238087e+00,  2.48189339e+00,
        -1.31888292e+00, -9.75826681e-01,  9.66404782e-01,
        -2.99663960e+00,  5.98988263e+00,  2.04866948e+00,
         1.71905842e+00,  8.14208799e+00,  1.84764528e+00,
         5.64625481e+00,  7.00855794e+00, -2.99297754e+00,
         5.84290613e+00,  1.84815553e+00,  2.68382418e+00,
         1.72048356e+00, -3.05413935e+00, -3.52392068e+00,
        -1.25914049e-01,  5.99178792e+00, -4.86319039e+00,
         1.77302273e+00,  5.23944542e+00,  7.30777582e+0